"""
Rubric-based LLM scorer for a single document sequence.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Any

from evaluator_service.adapters.azure_openai import chat_json
from evaluator_service.utils.pdf_extractor import extract_text_from_pdf


class RubricScorer:
    _DEFAULT_REASONING = "Judge response could not be parsed reliably."
    _DEFAULT_CRITERIA = [
        "coherence",
        "dependency_flow",
        "content_progression",
        "non_redundancy",
    ]

    def _normalize_documents(self, documents: list[str]) -> list[str]:
        normalized: list[str] = []
        for item in documents:
            candidate = (item or "").strip()
            if not candidate:
                normalized.append("")
                continue

            path = Path(candidate)
            if path.exists() and path.is_file() and path.suffix.lower() == ".pdf":
                text = extract_text_from_pdf(str(path))
                normalized.append((text or "").strip())
            else:
                normalized.append(candidate)
        return normalized

    @staticmethod
    def _format_sequence(documents: list[str]) -> str:
        parts: list[str] = []
        for idx, doc in enumerate(documents, start=1):
            parts.append(f"--- Document {idx} ---\n{(doc or '').strip()}")
        return "\n\n".join(parts).strip()

    def _build_prompt(self, documents: list[str]) -> str:
        sequence_content = self._format_sequence(documents)
        return f"""You are an expert evaluator of AI-generated document sequences.

You will be given a sequence of documents generated by an AI system.
Each document is meant to cover a topic in a logical series.

Evaluate the sequence on the following criteria, scoring each from 1 to 5:

Criteria definitions:
- Coherence (1-5): Each document flows naturally from the previous one.
  1 = completely disconnected, 5 = perfectly fluid transitions
- Dependency flow (1-5): Concepts introduced early are properly built upon later.
  1 = no dependency awareness, 5 = every concept is properly scaffolded
- Content progression (1-5): The sequence moves from foundational to advanced topics logically.
  1 = random order, 5 = perfect foundational-to-advanced progression
- Non-redundancy (1-5): Information is not repeated unnecessarily across documents.
  1 = heavy repetition, 5 = every document adds new information

Scoring anchors:
- 1: Very poor - major issues
- 2: Poor - noticeable issues
- 3: Acceptable - meets basic expectations
- 4: Good - minor issues only
- 5: Excellent - no issues

--- Document Sequence ---
{sequence_content}

Respond in this exact JSON format:
{{
  "scores": {{
    "coherence": 1-5,
    "dependency_flow": 1-5,
    "content_progression": 1-5,
    "non_redundancy": 1-5
  }},
  "reasoning": "Your detailed explanation covering all criteria"
}}

Be strict and consistent. Use the full range of the scale.
"""

    @staticmethod
    def _round2(value: float) -> float:
        return round(value, 2)

    @staticmethod
    def _safe_int_score(value: Any) -> int | None:
        if isinstance(value, bool):
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float) and value.is_integer():
            return int(value)
        return None

    def _parse_scores(self, data: dict[str, Any], criteria: list[str]) -> dict[str, int] | None:
        raw_scores = data.get("scores")
        if not isinstance(raw_scores, dict):
            return None

        parsed: dict[str, int] = {}
        for criterion in criteria:
            value = self._safe_int_score(raw_scores.get(criterion))
            if value is None or not (1 <= value <= 5):
                return None
            parsed[criterion] = value
        return parsed

    def run_single_scoring(self, documents: list[str], criteria: list[str]) -> dict[str, Any]:
        prompt = self._build_prompt(documents)
        attempts = 0
        max_attempts = 3
        last_reasoning = self._DEFAULT_REASONING

        while attempts < max_attempts:
            attempts += 1
            data = chat_json(
                system="You are a strict JSON evaluator. Output JSON only.",
                user=prompt,
                model="gpt-4o",
                temperature=0,
                max_output_tokens=1200,
            )

            reasoning = data.get("reasoning")
            if isinstance(reasoning, str) and reasoning.strip():
                last_reasoning = reasoning.strip()

            parsed_scores = self._parse_scores(data, criteria)
            if parsed_scores is None:
                continue

            return {"scores": parsed_scores, "reasoning": last_reasoning}

        # Graceful fallback if model never returns valid JSON payload
        fallback_scores = {criterion: 3 for criterion in criteria}
        return {"scores": fallback_scores, "reasoning": last_reasoning}

    def run_evaluation(self, sequence: dict[str, Any], criteria: list[str], runs: int) -> dict[str, Any]:
        selected_criteria = criteria or self._DEFAULT_CRITERIA
        documents = self._normalize_documents(sequence.get("documents", []))
        architecture = sequence.get("architecture", "unknown")

        if not documents:
            raise ValueError("sequence.documents must include at least one document.")

        run_details: list[dict[str, Any]] = []
        per_criterion_values: dict[str, list[int]] = {c: [] for c in selected_criteria}

        for idx in range(1, runs + 1):
            result = self.run_single_scoring(documents=documents, criteria=selected_criteria)
            scores: dict[str, int] = result["scores"]
            for criterion in selected_criteria:
                per_criterion_values[criterion].append(scores[criterion])

            run_details.append(
                {
                    "run": idx,
                    "scores": scores,
                    "reasoning": result.get("reasoning", self._DEFAULT_REASONING),
                }
            )

        mean_scores: dict[str, float] = {}
        std_scores: dict[str, float] = {}

        for criterion in selected_criteria:
            values = per_criterion_values[criterion]
            mean = sum(values) / len(values)
            var = sum((v - mean) ** 2 for v in values) / len(values)
            std = math.sqrt(var)
            mean_scores[criterion] = self._round2(mean)
            std_scores[criterion] = self._round2(std)

        all_scores: list[int] = []
        for criterion in selected_criteria:
            all_scores.extend(per_criterion_values[criterion])
        overall_mean = self._round2(sum(all_scores) / len(all_scores)) if all_scores else 0.0

        return {
            "architecture": architecture,
            "runs": runs,
            "mean_scores": mean_scores,
            "std_scores": std_scores,
            "overall_mean": overall_mean,
            "run_details": run_details,
        }
