name: Trigger auto deployment for eduflow-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/eduflow-frontend-AutoDeployTrigger-978c4819-2888-4382-a0c5-268c96ed1edb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EDUFLOWFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EDUFLOWFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EDUFLOWFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/dummy-ui
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: eduflow001-fuc3dpevgpbvdtgp.azurecr.io
          registryUsername: ${{ secrets.EDUFLOWFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EDUFLOWFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: eduflow-frontend
          resourceGroup: rg-eduflow-res-dev-001
          imageToBuild: eduflow001-fuc3dpevgpbvdtgp.azurecr.io/eduflow-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


